on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'yarn.lock'
      - 'eslint.config.mjs'
      - '.node-version'
      - '.github/workflows/build.yaml'

jobs:
  integrate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '21.x', '22.x', '23.x', '24.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache CDK Dependency
        uses: actions/cache@v4
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency-${{ matrix.node-version }}
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependency
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build
